name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ZIG_VERSION: 0.14.1

jobs:
  unit_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -y \
            git sudo binutils curl wget tar xz-utils

      - name: Install zig
        run: |
          curl https://ziglang.org/download/${{env.ZIG_VERSION}}/zig-x86_64-linux-${{env.ZIG_VERSION}}.tar.xz -L -o zig.tar.xz
          tar -xf zig.tar.xz
          echo "$(pwd)/zig-x86_64-linux-${{env.ZIG_VERSION}}" >> $GITHUB_PATH

      - name: Unit Tests
        run: |
          zig build test --summary all -Druntime_test=true
